# Generated by Django 6.0.6 on 2026-07-02 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('logo', models.ImageField(upload_to='logos/campeonatos/')),
                ('temporada', models.IntegerField()),
                ('tipo', models.CharField(choices=[('e', 'Estadual'), ('r', 'Regional'), ('n', 'Nacional'), ('c', 'Continental'), ('m', 'Mundial')], max_length=1)),
                ('data_inicio', models.DateField()),
                ('quantidade_equipes', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Clube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sigla', models.CharField(max_length=3)),
                ('logo', models.ImageField(upload_to='logos/clubes/')),
                ('tecnico', models.CharField(default='Interino', max_length=50)),
                ('fundacao', models.DateField()),
                ('estadio', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estatistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gols', models.IntegerField(blank=True, null=True)),
                ('chutes', models.IntegerField(blank=True, null=True)),
                ('chutes_a_gol', models.IntegerField(blank=True, null=True)),
                ('porcentagem_posse_de_bola', models.IntegerField(blank=True, null=True)),
                ('passes', models.IntegerField(blank=True, null=True)),
                ('porcentagem_precisao_de_passe', models.IntegerField(blank=True, null=True)),
                ('faltas', models.IntegerField(blank=True, null=True)),
                ('cartoes_amarelos', models.IntegerField(blank=True, null=True)),
                ('cartoes_vermelhos', models.IntegerField(blank=True, null=True)),
                ('escanteios', models.IntegerField(blank=True, null=True)),
                ('impedimentos', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('data_nascimento', models.DateField()),
                ('altura', models.DecimalField(decimal_places=2, max_digits=3)),
                ('peso', models.DecimalField(decimal_places=1, max_digits=3)),
                ('nacionalidade', models.CharField(max_length=40)),
                ('numero_camisa', models.PositiveIntegerField(default=0)),
                ('posicao_principal', models.CharField(choices=[('GK', 'Goleiro'), ('CB', 'Zagueiro Central'), ('LB', 'Lateral Esquerdo'), ('RB', 'Lateral Direito'), ('LWB', 'Lateral Ofensivo Esquerdo'), ('RWB', 'Lateral Ofensivo Direito'), ('DM', 'Volante'), ('CM', 'Meio Campo Central'), ('AM', 'Meia Ofensivo'), ('LM', 'Ala Esquerdo'), ('RM', 'Ala Direito'), ('LW', 'Ponta Esquerda'), ('RW', 'Ponta Direita'), ('CF', 'Centroavante'), ('ST', 'Atacante')], max_length=20)),
                ('clube', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elenco', to='competicoes.clube')),
            ],
        ),
        migrations.CreateModel(
            name='Participacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vitorias', models.PositiveIntegerField(default=0)),
                ('empates', models.PositiveIntegerField(default=0)),
                ('derrotas', models.PositiveIntegerField(default=0)),
                ('gols_feitos', models.PositiveIntegerField(default=0)),
                ('gols_sofridos', models.PositiveIntegerField(default=0)),
                ('cartoes_amarelos', models.PositiveIntegerField(default=0)),
                ('cartoes_vermelhos', models.PositiveIntegerField(default=0)),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes', to='competicoes.campeonato')),
                ('clube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes', to='competicoes.clube')),
            ],
            options={
                'unique_together': {('campeonato', 'clube')},
            },
        ),
        migrations.AddField(
            model_name='clube',
            name='campeonatos',
            field=models.ManyToManyField(related_name='clubes', through='competicoes.Participacao', to='competicoes.campeonato'),
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodada', models.IntegerField()),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('F', 'Finalizada'), ('A', 'Adiada')], default='P', max_length=20)),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='competicoes.campeonato')),
                ('estatisticas_mandante', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partida_como_estatisticas_mandante', to='competicoes.estatistica')),
                ('estatisticas_visitante', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partida_como_estatisticas_visitante', to='competicoes.estatistica')),
                ('mandante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_mandante', to='competicoes.participacao')),
                ('visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_visitante', to='competicoes.participacao')),
            ],
        ),
        migrations.CreateModel(
            name='Gol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minuto', models.PositiveIntegerField()),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gols', to='competicoes.atleta')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gols', to='competicoes.partida')),
            ],
        ),
        migrations.CreateModel(
            name='EscalacaoSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao_assumida', models.CharField(choices=[('GK', 'Goleiro'), ('CB', 'Zagueiro Central'), ('LB', 'Lateral Esquerdo'), ('RB', 'Lateral Direito'), ('LWB', 'Lateral Ofensivo Esquerdo'), ('RWB', 'Lateral Ofensivo Direito'), ('DM', 'Volante'), ('CM', 'Meio Campo Central'), ('AM', 'Meia Ofensivo'), ('LM', 'Ala Esquerdo'), ('RM', 'Ala Direito'), ('LW', 'Ponta Esquerda'), ('RW', 'Ponta Direita'), ('CF', 'Centroavante'), ('ST', 'Atacante')], max_length=20)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competicoes.atleta')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalacao_slots', to='competicoes.partida')),
            ],
        ),
    ]
