# Generated by Django 6.0.6 on 2026-06-14 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('logo', models.ImageField(upload_to='logos/campeonatos/')),
                ('temporada', models.IntegerField()),
                ('tipo', models.CharField(choices=[('e', 'Estadual'), ('r', 'Regional'), ('n', 'Nacional'), ('c', 'Continental'), ('m', 'Mundial')], max_length=1)),
                ('data_inicio', models.DateField()),
                ('quantidade_equipes', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Clube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sigla', models.CharField(max_length=3)),
                ('logo', models.ImageField(upload_to='logos/clubes/')),
                ('tecnico', models.CharField(default='Interino', max_length=50)),
                ('fundacao', models.DateField()),
                ('estadio', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos', models.PositiveIntegerField(default=0)),
                ('vitorias', models.PositiveIntegerField(default=0)),
                ('empates', models.PositiveIntegerField(default=0)),
                ('derrotas', models.PositiveIntegerField(default=0)),
                ('gols_feitos', models.PositiveIntegerField(default=0)),
                ('gols_sofridos', models.PositiveIntegerField(default=0)),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competicoes.campeonato')),
                ('clube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competicoes.clube')),
            ],
            options={
                'unique_together': {('campeonato', 'clube')},
            },
        ),
        migrations.AddField(
            model_name='clube',
            name='campeonatos',
            field=models.ManyToManyField(related_name='clubes', through='competicoes.Participacao', to='competicoes.campeonato'),
        ),
    ]
