# Generated by Django 6.0.6 on 2026-07-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competicoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atleta',
            name='numero_camisa',
            field=models.PositiveIntegerField(),
        ),
    ]
