# Generated by Django 6.0.6 on 2026-06-14 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competicoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participacao',
            name='campeonato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes', to='competicoes.campeonato'),
        ),
        migrations.AlterField(
            model_name='participacao',
            name='clube',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes', to='competicoes.clube'),
        ),
    ]
