# Generated by Django 6.0.6 on 2026-06-17 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competicoes', '0002_alter_participacao_campeonato_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estatistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gols', models.IntegerField(blank=True, null=True)),
                ('chutes', models.IntegerField(blank=True, null=True)),
                ('chutes_a_gol', models.IntegerField(blank=True, null=True)),
                ('porcentagem_posse_de_bola', models.IntegerField(blank=True, null=True)),
                ('passes', models.IntegerField(blank=True, null=True)),
                ('porcentagem_precisao_de_passe', models.IntegerField(blank=True, null=True)),
                ('faltas', models.IntegerField(blank=True, null=True)),
                ('cartoes_amarelos', models.IntegerField(blank=True, null=True)),
                ('cartoes_vermelhos', models.IntegerField(blank=True, null=True)),
                ('escanteios', models.IntegerField(blank=True, null=True)),
                ('impedimentos', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodada', models.IntegerField()),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('E', 'Em Andamento'), ('F', 'Finalizada')], default='P', max_length=20)),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='competicoes.campeonato')),
                ('estatisticas_mandante', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partida_como_estatisticas_mandante', to='competicoes.estatistica')),
                ('estatisticas_visitante', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partida_como_estatisticas_visitante', to='competicoes.estatistica')),
                ('mandante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_mandante', to='competicoes.participacao')),
                ('visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_visitante', to='competicoes.participacao')),
            ],
        ),
    ]
