# Generated by Django 6.0.6 on 2026-07-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competicoes', '0002_alter_atleta_numero_camisa'),
    ]

    operations = [
        migrations.AddField(
            model_name='escalacaoslot',
            name='estado',
            field=models.CharField(choices=[('T', 'Titular'), ('R', 'Reserva')], default='R', max_length=10),
        ),
    ]
