# Generated by Django 6.0.6 on 2026-07-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competicoes', '0003_escalacaoslot_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escalacaoslot',
            name='posicao_assumida',
            field=models.CharField(blank=True, choices=[('GK', 'Goleiro'), ('CB', 'Zagueiro Central'), ('LB', 'Lateral Esquerdo'), ('RB', 'Lateral Direito'), ('LWB', 'Lateral Ofensivo Esquerdo'), ('RWB', 'Lateral Ofensivo Direito'), ('DM', 'Volante'), ('CM', 'Meio Campo Central'), ('AM', 'Meia Ofensivo'), ('LM', 'Ala Esquerdo'), ('RM', 'Ala Direito'), ('LW', 'Ponta Esquerda'), ('RW', 'Ponta Direita'), ('CF', 'Centroavante'), ('ST', 'Atacante')], max_length=20, null=True),
        ),
    ]
