# Generated by Django 6.0.6 on 2026-06-18 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competicoes', '0003_estatistica_partida'),
    ]

    operations = [
        migrations.AddField(
            model_name='participacao',
            name='cartoes_amarelos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participacao',
            name='cartoes_vermelhos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='partida',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('F', 'Finalizada')], default='P', max_length=20),
        ),
    ]
