# Generated by Django 6.0.6 on 2026-06-21 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competicoes', '0006_escalacao_escalacaoslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='escalacao_mandante',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partida_como_escalacao_mandante', to='competicoes.escalacao'),
        ),
        migrations.AddField(
            model_name='partida',
            name='escalacao_visitante',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partida_como_escalacao_visitante', to='competicoes.escalacao'),
        ),
    ]
