# Generated by Django 6.0.6 on 2026-06-23 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competicoes', '0007_partida_escalacao_mandante_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EscalacaoSlot',
        ),
    ]
