# Generated by Django 6.0.6 on 2026-06-23 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competicoes', '0009_escalacaoslot'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EscalacaoSlot',
            new_name='EscalacaoSpace',
        ),
    ]
