# Generated by Django 6.0.6 on 2026-06-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competicoes', '0010_rename_escalacaoslot_escalacaospace'),
    ]

    operations = [
        migrations.AddField(
            model_name='participacao',
            name='partidas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
