# Generated by Django 6.0.6 on 2026-06-25 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competicoes', '0011_participacao_partidas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minuto', models.PositiveIntegerField()),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gols', to='competicoes.atleta')),
                ('clube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gols', to='competicoes.clube')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gols', to='competicoes.partida')),
            ],
        ),
    ]
