# Generated by Django 6.0.6 on 2026-06-25 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competicoes', '0012_gol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participacao',
            name='pontos',
        ),
    ]
