# Generated by Django 6.0.6 on 2026-06-25 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competicoes', '0013_remove_participacao_pontos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participacao',
            name='partidas',
        ),
    ]
