# Generated by Django 6.0.6 on 2026-06-26 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competicoes', '0014_remove_participacao_partidas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EscalacaoSpace',
            new_name='EscalacaoSlot',
        ),
    ]
