# Generated by Django 6.0.6 on 2026-06-26 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competicoes', '0015_rename_escalacaospace_escalacaoslot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gol',
            name='clube',
        ),
    ]
