# Generated by Django 6.0.6 on 2026-07-01 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competicoes', '0016_remove_gol_clube'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partida',
            name='escalacao_visitante',
        ),
        migrations.RemoveField(
            model_name='escalacaoslot',
            name='escalacao',
        ),
        migrations.RemoveField(
            model_name='partida',
            name='escalacao_mandante',
        ),
        migrations.AddField(
            model_name='escalacaoslot',
            name='partida',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='escalacao_slots', to='competicoes.partida'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Escalacao',
        ),
    ]
